### ISSUE TITLE
Data-Transfers are possible when provider changed his MDS-ID

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ce#1030] opened 2024-08-20 09:08 UTC
### Description - What happened? *

If the **provider** with the MDS ID XXX has a contract, which is successfully negotiated, and then changes the MDS ID to YYY on-the-fly without deleting the database it is further possible for the **consumer** to consume the data and the asset presentation and the contract history present the new (wrong) MDS ID YYY.

### Expected Behavior *

Data transaction shall be not possible due to the wrong MDS Id on the **provider** side.

### Observed Behavior *

Data transaction are still possible if **provider** MDS ID changed.

### Steps to Reproduce

- Start the on-prem provider connector with MDS ID XXX and create a contract offer with always free policy.
- From the consumer side: negotiate the offer.
- From the provider side: Change the MDS Id in the docker compose to YYY and re-start the connector without deleting the database
- From the provider side: Check that the MDS Id in the contract offer is changed to YYY
- From the consumer side: Try to consume the data. It is further possible.

**Comment by AbdullahMuk** [comment] 2024-08-26 07:38
Issue is caused because of core EDC 0.2.1 behaviour. Will be fixed when migrating to core EDC 0.6.x (or higher).

**Comment by AbdullahMuk** [comment] 2024-09-03 06:20
> Issue is caused because of core EDC 0.2.1 limitations and the scenario described is an edge-case. Will be fixed when migrating to core EDC 0.6.x (or higher).
> 
> /cc @jkbquabeck @tmberthold

@ip312 given the description of the causes, can we align that this issue will not be fixed within the current MDS CaaS based on core EDC 0.2.1 but rather it will be fixed when migrating MDS CaaS to core EDC 0.6.x (or higher)?

**Closed** 2024-11-20 14:31 UTC
Labels: kind/bug, scope/mds, bug/usability
